"""
Filter Coefficient Generator for ESP32-S3 EMG System
====================================================

Generates IIR filter coefficients for both 1000Hz and 2000Hz sampling rates.

Filters:
- High-Pass: 20 Hz, 4th-order Butterworth (2 biquad stages)
- Low-Pass: 450 Hz, 4th-order Butterworth (2 biquad stages)
- Notch: 50/60 Hz, 2nd-order IIR

Output: C++ header format ready for filters.cpp

Author: ESP32 Bionic Hand Project
Date: 2025
"""
import sys
if hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8', errors='replace')  # Windows console safety


import numpy as np
from scipy import signal
import os
import sys


def generate_coefficients(sampling_rate, powerline_freq=50):
    """
    Generate all filter coefficients for a given sampling rate.

    Args:
        sampling_rate: Sampling frequency in Hz (1000 or 2000)
        powerline_freq: Powerline frequency (50 or 60 Hz)

    Returns:
        Dictionary of filter coefficients
    """
    coeffs = {}

    # High-Pass Filter: 20 Hz, 4th-order Butterworth
    # Output as Second-Order Sections (SOS) for stability
    sos_hpf = signal.butter(4, 20, 'high', fs=sampling_rate, output='sos')
    coeffs['hpf'] = sos_hpf

    # Low-Pass Filter: 450 Hz, 4th-order Butterworth
    sos_lpf = signal.butter(4, 450, 'low', fs=sampling_rate, output='sos')
    coeffs['lpf'] = sos_lpf

    # Notch Filter: 50/60 Hz, Q=12.5
    b_notch, a_notch = signal.iirnotch(powerline_freq, Q=12.5, fs=sampling_rate)
    # Convert to SOS format (single biquad)
    sos_notch = np.array([[b_notch[0], b_notch[1], b_notch[2],
                           a_notch[0], a_notch[1], a_notch[2]]])
    coeffs['notch'] = sos_notch

    return coeffs


def sos_to_cpp_biquad(sos, var_prefix):
    """
    Convert SOS (Second-Order Sections) to C++ biquad coefficients.

    SOS format: [b0, b1, b2, a0, a1, a2]
    Normalized by a0 (a0=1.0)

    Args:
        sos: Second-order sections array
        var_prefix: Variable name prefix (e.g., 'HPF_STAGE1')

    Returns:
        C++ code string
    """
    cpp_code = []

    for stage_idx, section in enumerate(sos):
        b0, b1, b2, a0, a1, a2 = section

        # Normalize by a0
        b0_norm = b0 / a0
        b1_norm = b1 / a0
        b2_norm = b2 / a0
        a1_norm = a1 / a0
        a2_norm = a2 / a0

        stage_name = f"{var_prefix}_STAGE{stage_idx + 1}" if len(sos) > 1 else var_prefix

        cpp_code.append(f"  const float {stage_name}_B0 = {b0_norm:.10f}f;")
        cpp_code.append(f"  const float {stage_name}_B1 = {b1_norm:.10f}f;")
        cpp_code.append(f"  const float {stage_name}_B2 = {b2_norm:.10f}f;")
        cpp_code.append(f"  const float {stage_name}_A1 = {a1_norm:.10f}f;")
        cpp_code.append(f"  const float {stage_name}_A2 = {a2_norm:.10f}f;")
        cpp_code.append("")

    return "\n".join(cpp_code)


def print_frequency_response(sos, fs, title):
    """
    Print frequency response characteristics.

    Args:
        sos: Second-order sections
        fs: Sampling frequency
        title: Filter title
    """
    # Convert SOS to transfer function
    b, a = signal.sos2tf(sos)

    # Calculate frequency response
    w, h = signal.freqz(b, a, worN=2048, fs=fs)

    # Find -3dB point
    mag_db = 20 * np.log10(np.abs(h) + 1e-10)

    print(f"\n{title}:")
    print(f"  DC gain: {mag_db[0]:.2f} dB")
    print(f"  Nyquist gain: {mag_db[-1]:.2f} dB")

    # Find cutoff frequencies
    idx_3db = np.where(mag_db < -3.0)[0]
    if len(idx_3db) > 0:
        cutoff_freq = w[idx_3db[0]]
        print(f"  -3dB cutoff: {cutoff_freq:.1f} Hz")


def generate_cpp_header(coeffs_1000, coeffs_2000, powerline_freq):
    """
    Generate complete C++ header with all coefficients.

    Args:
        coeffs_1000: Coefficients for 1000 Hz sampling
        coeffs_2000: Coefficients for 2000 Hz sampling
        powerline_freq: Powerline frequency (50 or 60 Hz)

    Returns:
        C++ header string
    """
    header = f"""
/*
 * Auto-Generated Filter Coefficients
 * ===================================
 *
 * Generated by: generate_filter_coefficients.py
 * Powerline Frequency: {powerline_freq} Hz
 *
 * Filters:
 * - High-Pass: 20 Hz, 4th-order Butterworth (2 biquad stages)
 * - Low-Pass: 450 Hz, 4th-order Butterworth (2 biquad stages)
 * - Notch: {powerline_freq} Hz, Q=12.5 (1 biquad)
 *
 * The whole system samples at 1000 Hz (data acquisition and inference), so
 * the 1000 Hz set is the default. The 2000 Hz set is only compiled when
 * FILTER_SAMPLING_2000HZ is defined; it is kept for experiments.
 */
#ifndef FILTER_COEFFICIENTS_{powerline_freq}HZ_H
#define FILTER_COEFFICIENTS_{powerline_freq}HZ_H

#ifndef FILTER_SAMPLING_2000HZ
// ============================================================================
// 1000 Hz SAMPLING RATE (default)
// ============================================================================
#define FILTER_SAMPLING_RATE_HZ 1000

{sos_to_cpp_biquad(coeffs_1000['hpf'], 'HPF')}
{sos_to_cpp_biquad(coeffs_1000['lpf'], 'LPF')}
{sos_to_cpp_biquad(coeffs_1000['notch'], 'NOTCH')}
#else
// ============================================================================
// 2000 Hz SAMPLING RATE (experimental, FILTER_SAMPLING_2000HZ defined)
// ============================================================================
#define FILTER_SAMPLING_RATE_HZ 2000

{sos_to_cpp_biquad(coeffs_2000['hpf'], 'HPF')}
{sos_to_cpp_biquad(coeffs_2000['lpf'], 'LPF')}
{sos_to_cpp_biquad(coeffs_2000['notch'], 'NOTCH')}
#endif  // FILTER_SAMPLING_2000HZ

#endif  // FILTER_COEFFICIENTS_{powerline_freq}HZ_H
"""
    return header


def main():
    """Main function."""
    if len(sys.argv) > 1:
        powerline_freq = int(sys.argv[1])
        if powerline_freq not in [50, 60]:
            print("Error: Powerline frequency must be 50 or 60 Hz")
            sys.exit(1)
    else:
        powerline_freq = 50  # Default: Europe/Asia/Africa

    print("="*70)
    print("Filter Coefficient Generator")
    print("="*70)
    print(f"\nPowerline Frequency: {powerline_freq} Hz")
    print("Generating coefficients for 1000 Hz and 2000 Hz sampling rates...")

    # Generate coefficients for both sampling rates
    coeffs_1000 = generate_coefficients(1000, powerline_freq)
    coeffs_2000 = generate_coefficients(2000, powerline_freq)

    # Print frequency response characteristics
    print("\n" + "="*70)
    print("1000 Hz SAMPLING RATE")
    print("="*70)
    print_frequency_response(coeffs_1000['hpf'], 1000, "High-Pass (20 Hz)")
    print_frequency_response(coeffs_1000['lpf'], 1000, "Low-Pass (450 Hz)")
    print_frequency_response(coeffs_1000['notch'], 1000, f"Notch ({powerline_freq} Hz)")

    print("\n" + "="*70)
    print("2000 Hz SAMPLING RATE")
    print("="*70)
    print_frequency_response(coeffs_2000['hpf'], 2000, "High-Pass (20 Hz)")
    print_frequency_response(coeffs_2000['lpf'], 2000, "Low-Pass (450 Hz)")
    print_frequency_response(coeffs_2000['notch'], 2000, f"Notch ({powerline_freq} Hz)")

    # Generate C++ header
    cpp_header = generate_cpp_header(coeffs_1000, coeffs_2000, powerline_freq)

    # Save to file
    output_file = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "include", f"filter_coefficients_{powerline_freq}hz.h")
    with open(output_file, 'w') as f:
        f.write(cpp_header)

    print("\n" + "="*70)
    print(f"✅ Coefficients saved to: {output_file}")
    print("="*70)

    print("\n📋 Next Steps:")
    print(f"1. The header is written straight into include/ and picked up by filters.cpp")
    print(f"2. Update POWERLINE_FREQ_HZ in filters.h to {powerline_freq}")
    print(f"3. Verify coefficients compile without errors")
    print(f"4. Test filters with validate_filters.py")

    # Also print to stdout for easy copy-paste
    print("\n" + "="*70)
    print("C++ COEFFICIENTS (copy to filters.cpp):")
    print("="*70)
    print(cpp_header)


if __name__ == "__main__":
    main()
