// Auto-generated by export_model_header.py on 2026-09-16 19:50:52
// Metadata of the deployed model. Safe to include from every source file.
#ifndef MODEL_META_H
#define MODEL_META_H

#define MODEL_NUM_FEATURES 24
#define MODEL_NUM_CLASSES  11
#define REST_CLASS_INDEX   0
#define MODEL_MD5          "d89284efdaf24bc606b9ebe2351496db"
#define MODEL_DESCRIPTION  "TD4 MLP 256-128-64 float32, 6 sensors, trained 2025-11-26 00:33 (random split)"
#define MODEL_TRAINING_DATA "training_data_20251126_000759.csv (CORRUPTED: 87% uint16 overflow rows; placeholder until clean 11-class data is recorded)"
#define MODEL_NOTE         "audit 2026-09: placeholder model, retrain before use"
#define MODEL_TEST_ACCURACY 0.3750f

// Class order used for training. Index i of the softmax output == GESTURE_NAMES[i].
static const char* const GESTURE_NAMES[MODEL_NUM_CLASSES] = { "Rest", "Fist", "Open", "Point", "Victory", "OK", "ThumbUp", "ThumbDn", "Grasp", "Pinch", "WristFlex" };

#endif  // MODEL_META_H
