
/*
 * Auto-Generated Filter Coefficients
 * ===================================
 *
 * Generated by: generate_filter_coefficients.py
 * Powerline Frequency: 50 Hz
 *
 * Filters:
 * - High-Pass: 20 Hz, 4th-order Butterworth (2 biquad stages)
 * - Low-Pass: 450 Hz, 4th-order Butterworth (2 biquad stages)
 * - Notch: 50 Hz, Q=12.5 (1 biquad)
 *
 * UNIFIED 1000 Hz SAMPLING:
 * Both data_acquisition and real_time_inference now use 1000 Hz sampling.
 * The 1000 Hz coefficients below are used by default (DATA_ACQUISITION_MODE not defined).
 * The 2000 Hz coefficients are kept for future reference but currently unused.
 */

// ============================================================================
// 1000 Hz SAMPLING RATE (Real-Time Inference)
// ============================================================================
#ifndef DATA_ACQUISITION_MODE

  const float HPF_STAGE1_B0 = 0.8484752955f;
  const float HPF_STAGE1_B1 = -1.6969505910f;
  const float HPF_STAGE1_B2 = 0.8484752955f;
  const float HPF_STAGE1_A1 = -1.7783134881f;
  const float HPF_STAGE1_A2 = 0.7924474718f;

  const float HPF_STAGE2_B0 = 1.0000000000f;
  const float HPF_STAGE2_B1 = -2.0000000000f;
  const float HPF_STAGE2_B2 = 1.0000000000f;
  const float HPF_STAGE2_A1 = -1.8934156010f;
  const float HPF_STAGE2_A2 = 0.9084644129f;

  const float LPF_STAGE1_B0 = 0.6620158372f;
  const float LPF_STAGE1_B1 = 1.3240316744f;
  const float LPF_STAGE1_B2 = 0.6620158372f;
  const float LPF_STAGE1_A1 = 1.4796742169f;
  const float LPF_STAGE1_A2 = 0.5558215433f;

  const float LPF_STAGE2_B0 = 1.0000000000f;
  const float LPF_STAGE2_B1 = 2.0000000000f;
  const float LPF_STAGE2_B2 = 1.0000000000f;
  const float LPF_STAGE2_A1 = 1.7009643319f;
  const float LPF_STAGE2_A2 = 0.7884997398f;

  const float NOTCH_B0 = 0.9875889381f;
  const float NOTCH_B1 = -1.8785057900f;
  const float NOTCH_B2 = 0.9875889381f;
  const float NOTCH_A1 = -1.8785057900f;
  const float NOTCH_A2 = 0.9751778762f;

#endif  // !DATA_ACQUISITION_MODE

// ============================================================================
// 2000 Hz SAMPLING RATE (Data Acquisition)
// ============================================================================
#ifdef DATA_ACQUISITION_MODE

  const float HPF_STAGE1_B0 = 0.9211709935f;
  const float HPF_STAGE1_B1 = -1.8423419870f;
  const float HPF_STAGE1_B2 = 0.9211709935f;
  const float HPF_STAGE1_A1 = -1.8866095826f;
  const float HPF_STAGE1_A2 = 0.8903397363f;

  const float HPF_STAGE2_B0 = 1.0000000000f;
  const float HPF_STAGE2_B1 = -2.0000000000f;
  const float HPF_STAGE2_B2 = 1.0000000000f;
  const float HPF_STAGE2_A1 = -1.9492159580f;
  const float HPF_STAGE2_A2 = 0.9530698953f;

  const float LPF_STAGE1_B0 = 0.0675048060f;
  const float LPF_STAGE1_B1 = 0.1350096120f;
  const float LPF_STAGE1_B2 = 0.0675048060f;
  const float LPF_STAGE1_A1 = -0.1635911661f;
  const float LPF_STAGE1_A2 = 0.0457488768f;

  const float LPF_STAGE2_B0 = 1.0000000000f;
  const float LPF_STAGE2_B1 = 2.0000000000f;
  const float LPF_STAGE2_B2 = 1.0000000000f;
  const float LPF_STAGE2_A1 = -0.2270502871f;
  const float LPF_STAGE2_A2 = 0.4514083391f;

  const float NOTCH_B0 = 0.9937559650f;
  const float NOTCH_B1 = -1.9630423600f;
  const float NOTCH_B2 = 0.9937559650f;
  const float NOTCH_A1 = -1.9630423600f;
  const float NOTCH_A2 = 0.9875119299f;

#endif  // DATA_ACQUISITION_MODE
