
/*
 * Auto-Generated Filter Coefficients
 * ===================================
 *
 * Generated by: generate_filter_coefficients.py
 * Powerline Frequency: 50 Hz
 * Sampling Rate: 2000 Hz (Unified for both data acquisition and real-time inference)
 *
 * Filters:
 * - High-Pass: 20 Hz, 4th-order Butterworth (2 biquad stages)
 * - Low-Pass: 450 Hz, 4th-order Butterworth (2 biquad stages)
 * - Notch: 50 Hz, Q=12.5 (1 biquad)
 *
 * NOTE: These coefficients are directly embedded in filters.cpp
 * This file is kept for reference and Python script compatibility.
 */

#ifndef FILTER_COEFFICIENTS_50HZ_H
#define FILTER_COEFFICIENTS_50HZ_H

// ============================================================================
// 2000 Hz SAMPLING RATE (Unified)
// ============================================================================

// High-Pass Filter Stage 1 (20 Hz)
const float HPF_STAGE1_B0 = 0.9211709935f;
const float HPF_STAGE1_B1 = -1.8423419870f;
const float HPF_STAGE1_B2 = 0.9211709935f;
const float HPF_STAGE1_A1 = -1.8866095826f;
const float HPF_STAGE1_A2 = 0.8903397363f;

// High-Pass Filter Stage 2 (20 Hz)
const float HPF_STAGE2_B0 = 1.0000000000f;
const float HPF_STAGE2_B1 = -2.0000000000f;
const float HPF_STAGE2_B2 = 1.0000000000f;
const float HPF_STAGE2_A1 = -1.9492159580f;
const float HPF_STAGE2_A2 = 0.9530698953f;

// Low-Pass Filter Stage 1 (450 Hz)
const float LPF_STAGE1_B0 = 0.0675048060f;
const float LPF_STAGE1_B1 = 0.1350096120f;
const float LPF_STAGE1_B2 = 0.0675048060f;
const float LPF_STAGE1_A1 = -0.1635911661f;
const float LPF_STAGE1_A2 = 0.0457488768f;

// Low-Pass Filter Stage 2 (450 Hz)
const float LPF_STAGE2_B0 = 1.0000000000f;
const float LPF_STAGE2_B1 = 2.0000000000f;
const float LPF_STAGE2_B2 = 1.0000000000f;
const float LPF_STAGE2_A1 = -0.2270502871f;
const float LPF_STAGE2_A2 = 0.4514083391f;

// Notch Filter (50 Hz)
const float NOTCH_B0 = 0.9937559650f;
const float NOTCH_B1 = -1.9630423600f;
const float NOTCH_B2 = 0.9937559650f;
const float NOTCH_A1 = -1.9630423600f;
const float NOTCH_A2 = 0.9875119299f;

#endif  // FILTER_COEFFICIENTS_50HZ_H
