"""
Export a TFLite model to the two firmware headers
==================================================

  include/model.h       const unsigned char model_tflite[] (weights, flash)
  include/model_meta.h  class names, REST index, feature count, provenance

The firmware includes model.h from exactly one translation unit and
model_meta.h from everywhere. static_asserts in functions.h compare the
metadata with the firmware constants, so a model trained with the wrong
feature count or class order fails at compile time instead of at run time.

Usage:
  python export_model_header.py model.tflite --names Rest Fist ... --rest Rest \
      --num-features 24 --training-data data.csv --note "..." --out-dir ../../include
"""
import sys
if hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8', errors='replace')  # Windows console safety


import argparse
import hashlib
import os
import struct
from datetime import datetime


def _sanitize(s: str) -> str:
    return s.replace('\\', '/').replace('"', "'")


def export_headers(tflite_path, class_names, rest_name, num_features, out_dir,
                   training_data="unknown", note="", accuracy=None, feature_ranges=None,
                   description="TD4 MLP float32"):
    with open(tflite_path, 'rb') as f:
        data = f.read()
    if data[4:8] != b'TFL3':
        raise ValueError(f"{tflite_path} is not a TFLite flatbuffer (missing TFL3 identifier)")
    if rest_name not in class_names:
        raise ValueError(f"REST class '{rest_name}' not in class names {class_names}")
    rest_idx = class_names.index(rest_name)
    md5 = hashlib.md5(data).hexdigest()
    stamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')

    os.makedirs(out_dir, exist_ok=True)

    # ---- model.h -------------------------------------------------------------
    lines = []
    for i in range(0, len(data), 12):
        lines.append('  ' + ', '.join(f'0x{b:02x}' for b in data[i:i + 12]))
    model_h = f"""// Auto-generated by export_model_header.py on {stamp}
// Source: {_sanitize(os.path.basename(tflite_path))}  (md5 {md5})
// {_sanitize(description)}
// Include this file from ONE translation unit only (main.cpp).
#ifndef MODEL_H
#define MODEL_H

#include "model_meta.h"

const unsigned char model_tflite[] = {{
{",\n".join(lines)}
}};
const unsigned int model_tflite_len = {len(data)};

#endif  // MODEL_H
"""
    with open(os.path.join(out_dir, 'model.h'), 'w', encoding='utf-8') as f:
        f.write(model_h)

    # ---- model_meta.h --------------------------------------------------------
    names_c = ', '.join(f'"{_sanitize(n)}"' for n in class_names)
    ranges_c = ''
    if feature_ranges:
        ranges_c = '\n// Training feature ranges (min, max) per feature, for sanity checks\n'
        ranges_c += '#define MODEL_TRAIN_MAV_MAX %.6ff\n' % feature_ranges.get('mav_max', 0.0)
        ranges_c += '#define MODEL_TRAIN_WL_MAX  %.6ff\n' % feature_ranges.get('wl_max', 0.0)
    acc_c = f'#define MODEL_TEST_ACCURACY {accuracy:.4f}f\n' if accuracy is not None else ''
    meta_h = f"""// Auto-generated by export_model_header.py on {stamp}
// Metadata of the deployed model. Safe to include from every source file.
#ifndef MODEL_META_H
#define MODEL_META_H

#define MODEL_NUM_FEATURES {num_features}
#define MODEL_NUM_CLASSES  {len(class_names)}
#define REST_CLASS_INDEX   {rest_idx}
#define MODEL_MD5          "{md5}"
#define MODEL_DESCRIPTION  "{_sanitize(description)}"
#define MODEL_TRAINING_DATA "{_sanitize(training_data)}"
#define MODEL_NOTE         "{_sanitize(note)}"
{acc_c}{ranges_c}
// Class order used for training. Index i of the softmax output == GESTURE_NAMES[i].
static const char* const GESTURE_NAMES[MODEL_NUM_CLASSES] = {{ {names_c} }};

#endif  // MODEL_META_H
"""
    with open(os.path.join(out_dir, 'model_meta.h'), 'w', encoding='utf-8') as f:
        f.write(meta_h)

    print(f"model.h      -> {os.path.join(out_dir, 'model.h')}  ({len(data)} bytes, md5 {md5})")
    print(f"model_meta.h -> {os.path.join(out_dir, 'model_meta.h')}  classes={len(class_names)} rest={rest_idx} features={num_features}")
    return md5


def main():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument('tflite')
    p.add_argument('--names', nargs='+', required=True, help='class names in softmax order')
    p.add_argument('--rest', default='Rest', help='name of the rest class')
    p.add_argument('--num-features', type=int, required=True)
    p.add_argument('--training-data', default='unknown')
    p.add_argument('--note', default='')
    p.add_argument('--description', default='TD4 MLP float32')
    p.add_argument('--accuracy', type=float, default=None)
    p.add_argument('--out-dir', default=os.path.join(os.path.dirname(__file__), '..', '..', 'include'))
    a = p.parse_args()
    export_headers(a.tflite, a.names, a.rest, a.num_features, a.out_dir,
                   training_data=a.training_data, note=a.note, accuracy=a.accuracy,
                   description=a.description)


if __name__ == '__main__':
    main()
